### PR TITLE
:bug: Fix bug where app reads pasteboard on first launch to get CrossPaste source

### LINKED ISSUE #1874: A small BUG where the source application is wrong
### How frequently does the bug occur?

Always

### Description

在启动crossPaste的时候, 它会立马获取最近的一次剪切板的内容, 这个时候获取到的来源应用 其实往往是错误的.特别是因为刚启动,往往获取到的应用名字就是 CrossPaste本身.

image

分析源码: MacosPasteboardService

当程序启动的时候,把上次关闭时的剪切板的变更次数获取出来并赋值给changeCount变量(36行). 
然后调用run() 开启协程做剪切板的监控.  
通过swift的方法 获取到当前剪切板的变更次数currentChangeCount (66行), 并做对比. 
因为程序在没启动的时候剪切板变更过, 所以 这个时候 changeCount != currentChangeCount  (68行).
从而,触发了当前剪切板内容的获取,以及获取当前激活的应用的名字. 
这个时候获取到的应用名字,大概率就是CrossPaste自身,并不是真正的数据来源App.

从而触发这个BUG的产生. 

image

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

先关闭CrossPaste.  然后 在其他的应用中 复制数据.  而后再运行 CrossPaste.     

### Version

855f8ac3f

### OS

Macos

### PR DESCRIPTION
**Pull request by guiyanakuang**
close #1874

### CODE REVIEW

**Comment by guiyanakuang** [comment]
@sunxiang0918 Can you help review this patch

**Comment by sunxiang0918** [comment]
That's corrent.
However, since I don’t have access to Windows or Linux devices, I’m unsure if similar issues are present on other operating systems.

**Comment by guiyanakuang** [comment]
Pasteboard monitoring is more efficient on Windows and Linux. They both support listening callbacks, so this issue doesn't exist. However, Mac currently doesn't support this feature, and can only rely on periodic polling.

**Comment by guiyanakuang** [comment]
However, for the sake of consistency in functionality and user privacy concerns, I think we should perhaps add a switch to control whether to read the clipboard content set before the application starts, with this switch defaulting to false.

**Comment by guiyanakuang** [comment]
@sunxiang0918 Thanks for your review. I will merge this PR.

**Comment by sunxiang0918** [comment]
> However, for the sake of consistency in functionality and user privacy concerns, I think we should perhaps add a switch to control whether to read the clipboard content set before the application starts, with this switch defaulting to false.

Yes, I agree with this perspective as well. For instance, Paste on Mac doesn’t actually access previous records during startup.

**Pull request merged**
